import api from './api';

export interface ChatMessage {
  role: string;
  content: string;
}

export interface ChatRequest {
  messages: ChatMessage[];
  model: string;
  temperature?: number;
  max_tokens?: number;
}

export interface ChatResponse {
  content: string;
  model: string;
  usage: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
}

export interface Model {
  id: string;
  name: string;
  description: string;
}

const MOCK_MODELS: Model[] = [
  {
    id: "llama3-70b-8192",
    name: "Llama 3 70B",
    description: "Meta's Llama 3 70B model with 8192 context window"
  },
  {
    id: "llama3-8b-8192",
    name: "Llama 3 8B",
    description: "Meta's Llama 3 8B model with 8192 context window"
  },
  {
    id: "mixtral-8x7b-32768",
    name: "Mixtral 8x7B",
    description: "Mixtral 8x7B model with 32768 context window"
  },
  {
    id: "gemma-7b-it",
    name: "Gemma 7B",
    description: "Google's Gemma 7B instruction-tuned model"
  }
];

export const chatService = {
  sendMessage: async (request: ChatRequest): Promise<ChatResponse> => {
    if (import.meta.env.VITE_ENABLE_MOCK_AUTH === 'true' || localStorage.getItem('token') === "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtb2NrQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ1MjMyMDU1fQ.mock_signature") {
      console.log('Using mock chat implementation');
      
      const mockResponse: ChatResponse = {
        content: `This is a mock response from the AI assistant using the ${request.model} model. In a real implementation, this would be generated by Groq AI.`,
        model: request.model,
        usage: {
          prompt_tokens: 100,
          completion_tokens: 150,
          total_tokens: 250
        }
      };
      
      await new Promise(resolve => setTimeout(resolve, 500));
      
      return mockResponse;
    }
    
    const response = await api.post('/api/chat', request);
    return response.data;
  },
  
  getModels: async (): Promise<Model[]> => {
    if (import.meta.env.VITE_ENABLE_MOCK_AUTH === 'true' || localStorage.getItem('token') === "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtb2NrQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ1MjMyMDU1fQ.mock_signature") {
      console.log('Using mock models implementation');
      
      await new Promise(resolve => setTimeout(resolve, 300));
      
      return MOCK_MODELS;
    }
    
    const response = await api.get('/api/models');
    return response.data.models;
  }
};
